### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Bandit-code** [Itz-Hyperz/RandyAccIDs#13]
At least tell them how i am not a snowflake also update this tooo JimmyAccIds also i love people thinking i am bad i am like poison bro

**Comment by Bandit-code** [comment]
Also you sent  people my face you stick

**Comment by Itz-Hyperz** [comment]
I do just want you to know, [@Jekeltor](https://github.com/jekeltor) has integrated TrollGuard with his websites, now if you are TG banned, you cannot buy from him, or anyone else, with the latest PayPal template update 🤣

**Comment by Bandit-code** [comment]
> I do just want you to know, [@Jekeltor](https://github.com/jekeltor) has integrated TrollGuard with his websites, now if you are TG banned, you cannot buy from him, or anyone else, with the latest PayPal template update 🤣

idc
